### ISSUE TITLE
Esp32

### ISSUE THREAD

**Issue by djeepp5** [PsychoMnts/Xiaomi-Scooter-Motion-Control#1]
I think the best option is to emulate the potentiometer with for example the esp32 / esp8266 microcontroller, and use option 2 (because an accelerometer can be pretty inaccurate). 

It might even be possible to emulate the potentiometer in the serial connection.

**Comment by PsychoMnts** [comment]
I agree that the accelerometer option might be unreliable, as there is no way to measure the speed. 
The software must wait until the speed is 5 km/h before it can open the throttle, which is impossible to do with an accelerometer.

My goal is to keep the project as simple as possible. So a basic arduino should be able to do the job. 
But an esp32 / esp8266 would give some extra features like the possibility to adjust parameters on the fly using your phone.

**Comment by PsychoMnts** [comment]
The hardware will be ESP32 / ESP8266
