### ISSUE TITLE
Limit speed?

### ISSUE THREAD

**Issue by HJADR** [PsychoMnts/Xiaomi-Scooter-Motion-Control#5]
Hey,
I started using this script for the fun but ever since I did I cannot exceed 25km/h even with the costume scooter firmware that should allow me to go (way) over.  I cannot recognize a speed limit in this script, but just checking.

**Comment by PsychoMnts** [comment]
Hi,
The speed is not limited by the arduino code.
Xiaomi scooters cannot go much faster. (Also, not a smart thing to do)
Also check your tire presure and if you have an aerodynamic haircut.
