### ISSUE TITLE
Error 14 on Mi Pro 2 

### ISSUE THREAD

**Issue by Pixel-pix** [PsychoMnts/Xiaomi-Scooter-Motion-Control#6]
Good afternoon,

Followed the guide and succesfully flashed and uploaded the V1.3 file to my Nano.
Adjusted the scooter parameter to #2 to reflect the pro 2 setting..

But on boot it gives me the code 14 error.

Please advise.

**Comment by jkeijner** [comment]
same with the 1s.

**Comment by PsychoMnts** [comment]
Check your wiring. Error 14 means that the throttle wire doesn't get signal.
